In [1]:
import pandas as pd
import numpy as np

In [2]:
mov=pd.read_csv('imdb_top_1000.csv')

In [3]:
mov.head(10)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
6,https://m.media-amazon.com/images/M/MV5BNGNhMD...,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
9,https://m.media-amazon.com/images/M/MV5BMmEzNT...,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"

In [4]:
mov.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

In [5]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [6]:
mov.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [7]:
mov.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [8]:
mov=mov[['Poster_Link', 'Series_Title', 'Genre', 'Overview']]

In [9]:
mov

,Poster_Link,Series_Title,Genre,Overview
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...
...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,"Comedy, Drama, Romance",A young New York socialite becomes interested ...
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,"Drama, Western",Sprawling epic covering the life of a Texas ca...
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,"Drama, Romance, War","In Hawaii in 1941, a private is cruelly punish..."
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,"Drama, War",Several survivors of a torpedoed merchant ship...
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,"Crime, Mystery, Thriller",A man in London tries to help a counter-espion...

In [10]:
mov['tags'] = mov['Overview']+mov['Genre']
mov

,Poster_Link,Series_Title,Genre,Overview,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Drama,Two imprisoned men bond over a number of years...,Two imprisoned men bond over a number of years...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,"Crime, Drama",An organized crime dynasty's aging patriarch t...,An organized crime dynasty's aging patriarch t...
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,When the menace known as the Joker wreaks havo...
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,"Crime, Drama",The early life and career of Vito Corleone in ...,The early life and career of Vito Corleone in ...
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,"Crime, Drama",A jury holdout attempts to prevent a miscarria...,A jury holdout attempts to prevent a miscarria...
...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,"Comedy, Drama, Romance",A young New York socialite becomes interested ...,A young New York socialite becomes interested ...
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,"Drama, Western",Sprawling epic covering the life of a Texas ca...,Sprawling epic covering the life of a Texas ca...
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,"Drama, Romance, War","In Hawaii in 1941, a private is cruelly punish...","In Hawaii in 1941, a private is cruelly punish..."
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,"Drama, War",Several survivors of a torpedoed merchant ship...,Several survivors of a torpedoed merchant ship...
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,"Crime, Mystery, Thriller",A man in London tries to help a counter-espion...,A man in London tries to help a counter-espion...

In [11]:
new_data  = mov.drop(columns=['Overview', 'Genre'])
new_data

,Poster_Link,Series_Title,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Two imprisoned men bond over a number of years...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,An organized crime dynasty's aging patriarch t...
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,When the menace known as the Joker wreaks havo...
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,The early life and career of Vito Corleone in ...
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,A jury holdout attempts to prevent a miscarria...
...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,A young New York socialite becomes interested ...
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,Sprawling epic covering the life of a Texas ca...
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish..."
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,Several survivors of a torpedoed merchant ship...
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,A man in London tries to help a counter-espion...

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv=CountVectorizer(max_features=10000, stop_words='english')
cv

CountVectorizer(max_features=10000, stop_words='english')

In [14]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()
vector.shape

(1000, 5432)

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity

array([[1.        , 0.07161149, 0.06201737, ..., 0.06726728, 0.06362848,
        0.        ],
       [0.07161149, 1.        , 0.17320508, ..., 0.06262243, 0.05923489,
        0.09759001],
       [0.06201737, 0.17320508, 1.        , ..., 0.05423261, 0.05129892,
        0.04225771],
       ...,
       [0.06726728, 0.06262243, 0.05423261, ..., 1.        , 0.16692447,
        0.        ],
       [0.06362848, 0.05923489, 0.05129892, ..., 0.16692447, 1.        ,
        0.        ],
       [0.        , 0.09759001, 0.04225771, ..., 0.        , 0.        ,
        1.        ]])

In [16]:
new_data[new_data['Series_Title']=="The Godfather"].index[0]

1

In [17]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].Series_Title)

The Dark Knight
Batman Begins
Kill Bill: Vol. 1
Baby Driver
The Dark Knight Rises

In [18]:
def recommand(movies):
    index=new_data[new_data['Series_Title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].Series_Title)

In [19]:
recommand("Iron Man")

Iron Man
The Avengers
The Fifth Element
Predator
Captain America: Civil War

In [20]:
import pickle

In [21]:
pickle.dump(new_data, open('movies_list_imdb.pkl', 'wb'))

In [22]:
pickle.dump(similarity, open('similarity_imdb.pkl', 'wb'))

In [23]:
pickle.load(open('movies_list_imdb.pkl', 'rb'))

,Poster_Link,Series_Title,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,Two imprisoned men bond over a number of years...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,An organized crime dynasty's aging patriarch t...
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,When the menace known as the Joker wreaks havo...
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,The early life and career of Vito Corleone in ...
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,A jury holdout attempts to prevent a miscarria...
...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,A young New York socialite becomes interested ...
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,Sprawling epic covering the life of a Texas ca...
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,"In Hawaii in 1941, a private is cruelly punish..."
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,Several survivors of a torpedoed merchant ship...
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,A man in London tries to help a counter-espion...